.TH MYSTRFUNCTIONS 3 "September 2026" "1.0" "Library Functions Manual"
.SH NAME
mystrfunctions \- custom string manipulation functions for OS project
.SH SYNOPSIS
.nf
\fB#include <mystrfunctions.h>\fR

\fBint mystrlen(const char *\fIs\fB);\fR
\fBint mystrcpy(char *\fIdest\fB, const char *\fIsrc\fB);\fR
\fBint mystrncpy(char *\fIdest\fB, const char *\fIsrc\fB, int \fIn\fB);\fR
\fBint mystrcat(char *\fIdest\fB, const char *\fIsrc\fB);\fR
.fi
.SH DESCRIPTION
These functions are a custom implementation of standard C string operations created for an Operating Systems assignment. 
.SH AUTHOR
Written by OS Student.
